// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.6.1
// source: flight_operator.proto

package flight

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Status int32

const (
	Status_UNKNOWN     Status = 0
	Status_ON_ROUTE    Status = 1
	Status_ON_BOARDING Status = 2
	Status_DELAYED     Status = 3
	Status_CANCELED    Status = 4
	Status_SCHEDULED   Status = 5
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "ON_ROUTE",
		2: "ON_BOARDING",
		3: "DELAYED",
		4: "CANCELED",
		5: "SCHEDULED",
	}
	Status_value = map[string]int32{
		"UNKNOWN":     0,
		"ON_ROUTE":    1,
		"ON_BOARDING": 2,
		"DELAYED":     3,
		"CANCELED":    4,
		"SCHEDULED":   5,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_flight_operator_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_flight_operator_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_flight_operator_proto_rawDescGZIP(), []int{0}
}

type FlightDetailsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FlightDetailsRequest) Reset() {
	*x = FlightDetailsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flight_operator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlightDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightDetailsRequest) ProtoMessage() {}

func (x *FlightDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flight_operator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightDetailsRequest.ProtoReflect.Descriptor instead.
func (*FlightDetailsRequest) Descriptor() ([]byte, []int) {
	return file_flight_operator_proto_rawDescGZIP(), []int{0}
}

func (x *FlightDetailsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FlightDetailsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Terminal   int32  `protobuf:"varint,2,opt,name=terminal,proto3" json:"terminal,omitempty"`
	LastStatus Status `protobuf:"varint,3,opt,name=last_status,json=lastStatus,proto3,enum=Status" json:"last_status,omitempty"`
}

func (x *FlightDetailsResponse) Reset() {
	*x = FlightDetailsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flight_operator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlightDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightDetailsResponse) ProtoMessage() {}

func (x *FlightDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flight_operator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightDetailsResponse.ProtoReflect.Descriptor instead.
func (*FlightDetailsResponse) Descriptor() ([]byte, []int) {
	return file_flight_operator_proto_rawDescGZIP(), []int{1}
}

func (x *FlightDetailsResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FlightDetailsResponse) GetTerminal() int32 {
	if x != nil {
		return x.Terminal
	}
	return 0
}

func (x *FlightDetailsResponse) GetLastStatus() Status {
	if x != nil {
		return x.LastStatus
	}
	return Status_UNKNOWN
}

type DeparturesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeparturesRequest) Reset() {
	*x = DeparturesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flight_operator_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeparturesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeparturesRequest) ProtoMessage() {}

func (x *DeparturesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flight_operator_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeparturesRequest.ProtoReflect.Descriptor instead.
func (*DeparturesRequest) Descriptor() ([]byte, []int) {
	return file_flight_operator_proto_rawDescGZIP(), []int{2}
}

type DeparturesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeparturesResponse) Reset() {
	*x = DeparturesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flight_operator_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeparturesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeparturesResponse) ProtoMessage() {}

func (x *DeparturesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flight_operator_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeparturesResponse.ProtoReflect.Descriptor instead.
func (*DeparturesResponse) Descriptor() ([]byte, []int) {
	return file_flight_operator_proto_rawDescGZIP(), []int{3}
}

func (x *DeparturesResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TravelUpdatesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LastStatus Status `protobuf:"varint,3,opt,name=last_status,json=lastStatus,proto3,enum=Status" json:"last_status,omitempty"`
}

func (x *TravelUpdatesRequest) Reset() {
	*x = TravelUpdatesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flight_operator_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TravelUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TravelUpdatesRequest) ProtoMessage() {}

func (x *TravelUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flight_operator_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TravelUpdatesRequest.ProtoReflect.Descriptor instead.
func (*TravelUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_flight_operator_proto_rawDescGZIP(), []int{4}
}

func (x *TravelUpdatesRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TravelUpdatesRequest) GetLastStatus() Status {
	if x != nil {
		return x.LastStatus
	}
	return Status_UNKNOWN
}

type TravelUpdatesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TravelUpdatesResponse) Reset() {
	*x = TravelUpdatesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flight_operator_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TravelUpdatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TravelUpdatesResponse) ProtoMessage() {}

func (x *TravelUpdatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flight_operator_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TravelUpdatesResponse.ProtoReflect.Descriptor instead.
func (*TravelUpdatesResponse) Descriptor() ([]byte, []int) {
	return file_flight_operator_proto_rawDescGZIP(), []int{5}
}

type SupportChatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TravelerId string `protobuf:"bytes,1,opt,name=traveler_id,json=travelerId,proto3" json:"traveler_id,omitempty"`
	Message    string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SupportChatRequest) Reset() {
	*x = SupportChatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flight_operator_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SupportChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportChatRequest) ProtoMessage() {}

func (x *SupportChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flight_operator_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportChatRequest.ProtoReflect.Descriptor instead.
func (*SupportChatRequest) Descriptor() ([]byte, []int) {
	return file_flight_operator_proto_rawDescGZIP(), []int{6}
}

func (x *SupportChatRequest) GetTravelerId() string {
	if x != nil {
		return x.TravelerId
	}
	return ""
}

func (x *SupportChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SupportChatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerSupportId string `protobuf:"bytes,1,opt,name=customer_support_id,json=customerSupportId,proto3" json:"customer_support_id,omitempty"`
	Message           string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SupportChatResponse) Reset() {
	*x = SupportChatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flight_operator_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SupportChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportChatResponse) ProtoMessage() {}

func (x *SupportChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flight_operator_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportChatResponse.ProtoReflect.Descriptor instead.
func (*SupportChatResponse) Descriptor() ([]byte, []int) {
	return file_flight_operator_proto_rawDescGZIP(), []int{7}
}

func (x *SupportChatResponse) GetCustomerSupportId() string {
	if x != nil {
		return x.CustomerSupportId
	}
	return ""
}

func (x *SupportChatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_flight_operator_proto protoreflect.FileDescriptor

var file_flight_operator_proto_rawDesc = []byte{
	0x0a, 0x15, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x26, 0x0a, 0x14, 0x46, 0x6c, 0x69, 0x67, 0x68,
	0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x6d, 0x0a, 0x15, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x65, 0x72, 0x6d,
	0x69, 0x6e, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x74, 0x65, 0x72, 0x6d,
	0x69, 0x6e, 0x61, 0x6c, 0x12, 0x28, 0x0a, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x07, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x0a, 0x6c, 0x61, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x13,
	0x0a, 0x11, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x24, 0x0a, 0x12, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x50, 0x0a, 0x14, 0x54, 0x72, 0x61,
	0x76, 0x65, 0x6c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x28, 0x0a, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x07, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x0a, 0x6c, 0x61, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x17, 0x0a, 0x15, 0x54,
	0x72, 0x61, 0x76, 0x65, 0x6c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4f, 0x0a, 0x12, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x43,
	0x68, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x72,
	0x61, 0x76, 0x65, 0x6c, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x74, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x5f, 0x0a, 0x13, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74,
	0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x13,
	0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x63, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0x5e, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0c, 0x0a,
	0x08, 0x4f, 0x4e, 0x5f, 0x52, 0x4f, 0x55, 0x54, 0x45, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x4f,
	0x4e, 0x5f, 0x42, 0x4f, 0x41, 0x52, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07,
	0x44, 0x45, 0x4c, 0x41, 0x59, 0x45, 0x44, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x41, 0x4e,
	0x43, 0x45, 0x4c, 0x45, 0x44, 0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x43, 0x48, 0x45, 0x44,
	0x55, 0x4c, 0x45, 0x44, 0x10, 0x05, 0x32, 0x91, 0x02, 0x0a, 0x0e, 0x46, 0x6c, 0x69, 0x67, 0x68,
	0x74, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x40, 0x0a, 0x0d, 0x46, 0x6c, 0x69,
	0x67, 0x68, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x15, 0x2e, 0x46, 0x6c, 0x69,
	0x67, 0x68, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x0a, 0x44,
	0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x73, 0x12, 0x12, 0x2e, 0x44, 0x65, 0x70, 0x61,
	0x72, 0x74, 0x75, 0x72, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e,
	0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x42, 0x0a, 0x0d, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x12, 0x15, 0x2e, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x12, 0x3e, 0x0a, 0x0b, 0x53, 0x75,
	0x70, 0x70, 0x6f, 0x72, 0x74, 0x43, 0x68, 0x61, 0x74, 0x12, 0x13, 0x2e, 0x53, 0x75, 0x70, 0x70,
	0x6f, 0x72, 0x74, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14,
	0x2e, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x3b,
	0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_flight_operator_proto_rawDescOnce sync.Once
	file_flight_operator_proto_rawDescData = file_flight_operator_proto_rawDesc
)

func file_flight_operator_proto_rawDescGZIP() []byte {
	file_flight_operator_proto_rawDescOnce.Do(func() {
		file_flight_operator_proto_rawDescData = protoimpl.X.CompressGZIP(file_flight_operator_proto_rawDescData)
	})
	return file_flight_operator_proto_rawDescData
}

var file_flight_operator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_flight_operator_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_flight_operator_proto_goTypes = []interface{}{
	(Status)(0),                   // 0: Status
	(*FlightDetailsRequest)(nil),  // 1: FlightDetailsRequest
	(*FlightDetailsResponse)(nil), // 2: FlightDetailsResponse
	(*DeparturesRequest)(nil),     // 3: DeparturesRequest
	(*DeparturesResponse)(nil),    // 4: DeparturesResponse
	(*TravelUpdatesRequest)(nil),  // 5: TravelUpdatesRequest
	(*TravelUpdatesResponse)(nil), // 6: TravelUpdatesResponse
	(*SupportChatRequest)(nil),    // 7: SupportChatRequest
	(*SupportChatResponse)(nil),   // 8: SupportChatResponse
}
var file_flight_operator_proto_depIdxs = []int32{
	0, // 0: FlightDetailsResponse.last_status:type_name -> Status
	0, // 1: TravelUpdatesRequest.last_status:type_name -> Status
	1, // 2: FlightOperator.FlightDetails:input_type -> FlightDetailsRequest
	3, // 3: FlightOperator.Departures:input_type -> DeparturesRequest
	5, // 4: FlightOperator.TravelUpdates:input_type -> TravelUpdatesRequest
	7, // 5: FlightOperator.SupportChat:input_type -> SupportChatRequest
	2, // 6: FlightOperator.FlightDetails:output_type -> FlightDetailsResponse
	4, // 7: FlightOperator.Departures:output_type -> DeparturesResponse
	6, // 8: FlightOperator.TravelUpdates:output_type -> TravelUpdatesResponse
	8, // 9: FlightOperator.SupportChat:output_type -> SupportChatResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_flight_operator_proto_init() }
func file_flight_operator_proto_init() {
	if File_flight_operator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_flight_operator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlightDetailsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flight_operator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlightDetailsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flight_operator_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeparturesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flight_operator_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeparturesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flight_operator_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TravelUpdatesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flight_operator_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TravelUpdatesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flight_operator_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SupportChatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flight_operator_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SupportChatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_flight_operator_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_flight_operator_proto_goTypes,
		DependencyIndexes: file_flight_operator_proto_depIdxs,
		EnumInfos:         file_flight_operator_proto_enumTypes,
		MessageInfos:      file_flight_operator_proto_msgTypes,
	}.Build()
	File_flight_operator_proto = out.File
	file_flight_operator_proto_rawDesc = nil
	file_flight_operator_proto_goTypes = nil
	file_flight_operator_proto_depIdxs = nil
}
